class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Sweezen Foundation',
      'tagline': 'SECTION 8 NON-PROFIT | UN SDG ALIGNED',
      'hero_heading': 'Your ₹1000 can change a life today',
      'hero_sub': 'Join thousands of donors empowering rural communities with healthcare, education, and environmental programs.',
      'btn_donate_now': 'BE THE REASON SOMEONE SMILES',
      'btn_see_impact': 'SEE OUR IMPACT',
      'nav_home': 'Home',
      'nav_projects': 'Projects',
      'nav_donate': 'Donate',
      'nav_volunteer': 'Volunteer',
      'nav_profile': 'Profile',
      'stat_projects': 'ACTIVE PROJECTS',
      'stat_beneficiaries': 'LIVES TOUCHED',
      'stat_volunteers': 'VOLUNTEERS',
      'stat_districts': 'DISTRICTS COVERED',
      'stat_funds': 'FUNDS RAISED',
      'featured_projects': 'Featured Projects',
      'upcoming_events': 'Upcoming Events',
      'latest_news': 'Latest Updates',
      'humanity_card': 'Humanity Smart ID',
      'ask_sweezen': 'Ask Sweezen AI',
      'tax_benefit': '80G Tax Exemption Available',
      'login': 'Login / Register',
      'role_volunteer': 'Volunteer',
      'role_donor': 'Donor',
      'role_beneficiary': 'Beneficiary',
      'select_language': 'Select App Language (12 Languages)',
      'csr_dashboard': 'CSR Partner Dashboard',
      'hospital_education_portal': 'Hospital & Education Portals',
      'ai_analytics': 'AI-assisted Analytics',
      'accessibility_settings': 'Accessibility & Font Scale',
      'drawer_events': 'Events & Conclaves',
      'drawer_impact_map': 'Impact Map & Transparency',
      'drawer_communication': 'Communication Center',
      'drawer_reports': 'Reports & Media',
      'drawer_logout': 'Logout Account',
      'health_camps': 'Health Camps',
      'docs_and_receipts': 'Docs & Receipts',
      'realtime_impact': 'REAL-TIME FOUNDATION IMPACT',
      'specialized_portals': 'SPECIALIZED PORTALS & ANALYTICS',
      'view_all': 'View All',
      'personal_info_header': 'PERSONAL & ACCOUNT INFORMATION',
      'phone_number': 'Phone Number',
      'primary_location': 'Primary Location',
      'availability_schedule': 'Availability Schedule',
      'verified_documents': 'VERIFIED DOCUMENTS',
      'upload_new': 'UPLOAD NEW',
      'security_app_lock': 'SECURITY & APP LOCK',
      'fingerprint_lock': 'Fingerprint App Lock',
      'fingerprint_sub': 'Lock app locally using biometric fingerprint / PIN',
      'google_2fa': 'Google 2FA Authenticator',
      'google_2fa_sub': 'Bind 2FA TOTP QR code for account login',
      'app_prefs_lang': 'APP PREFERENCES & LANGUAGE',
      'app_language': 'App Language',
      'logout_account': 'LOGOUT ACCOUNT',
      'csr_proposals': 'Proposals',
      'csr_budgets': 'Approved Budgets',
      'csr_milestones': 'Milestones',
      'csr_utilization': 'Utilization Reports',
      'new_proposal': 'New CSR Proposal',
      'partner_registrations': 'Partner Registrations',
      'referrals': 'Referrals',
      'camp_schedules': 'Camp Schedules',
      'student_progress': 'Student Progress',
      'submit_referral': 'Submit Referral',
      'register_partner': 'Register Partner',
      'report_summaries': 'Report Summaries',
      'data_anomalies': 'Data Anomalies',
      'draft_impact_reports': 'Draft Impact Reports',
      'approve_publish': 'Approve & Publish Report',
      'accessibility_title': 'Accessibility & Easy Navigation',
      'text_scale_title': 'Text Size Scale',
      'high_contrast_title': 'High Contrast Mode (WCAG AAA)',
      'high_contrast_sub': 'Enhances colors, borders, and text readability for low-vision users.',
      'screen_reader_notice': 'TalkBack / VoiceOver screen-reader semantic labels enabled across all forms, buttons, and navigation.',
    },
    'hi': {
      'app_title': 'स्वीजन फाउंडेशन',
      'tagline': 'धारा 8 गैर-लाभकारी | संयुक्त राष्ट्र SDG संरेखित',
      'hero_heading': 'आपका ₹1000 आज किसी का जीवन बदल सकता है',
      'hero_sub': 'स्वास्थ्य सेवा, शिक्षा और पर्यावरण कार्यक्रमों के साथ ग्रामीण समुदायों को सशक्त बनाने वाले हजारों दाताओं से जुड़ें।',
      'btn_donate_now': 'किसी की मुस्कान का कारण बनें',
      'btn_see_impact': 'हमारा प्रभाव देखें',
      'nav_home': 'होम',
      'nav_projects': 'प्रोजेक्ट्स',
      'nav_donate': 'दान करें',
      'nav_volunteer': 'स्वयंसेवक',
      'nav_profile': 'प्रोफाइल',
      'stat_projects': 'सक्रिय प्रोजेक्ट्स',
      'stat_beneficiaries': 'लाभार्थी',
      'stat_volunteers': 'स्वयंसेवक',
      'stat_districts': 'जिले',
      'stat_funds': 'एकत्रित राशि',
      'featured_projects': 'प्रमुख परियोजनाएं',
      'upcoming_events': 'आगामी कार्यक्रम',
      'latest_news': 'नवीनतम समाचार',
      'humanity_card': 'ह्यूमैनिटी स्मार्ट आईडी',
      'ask_sweezen': 'स्वीजन AI से पूछें',
      'tax_benefit': '80G आयकर छूट उपलब्ध',
      'login': 'लॉगिन / पंजीकरण',
      'role_volunteer': 'स्वयंसेवक',
      'role_donor': 'दाता',
      'role_beneficiary': 'लाभार्थी',
      'select_language': 'ऐप भाषा चुनें (12 भाषाएं)',
      'csr_dashboard': 'सीएसआर पार्टनर डैशबोर्ड',
      'hospital_education_portal': 'अस्पताल एवं शिक्षा पोर्टल',
      'ai_analytics': 'एआई-सहायक विश्लेषिकी',
      'accessibility_settings': 'सुगम्यता एवं फ़ॉन्ट आकार',
      'drawer_events': 'कार्यक्रम एवं सम्मेलन',
      'drawer_impact_map': 'प्रभाव मानचित्र एवं पारदर्शिता',
      'drawer_communication': 'संचार केंद्र',
      'drawer_reports': 'रिपोर्ट एवं मीडिया',
      'drawer_logout': 'खाता लॉगआउट करें',
      'health_camps': 'स्वास्थ्य शिविर',
      'docs_and_receipts': 'दस्तावेज़ एवं रसीदें',
      'realtime_impact': 'फाउंडेशन का वास्तविक समय प्रभाव',
      'specialized_portals': 'विशेष पोर्टल एवं विश्लेषिकी',
      'view_all': 'सभी देखें',
      'personal_info_header': 'व्यक्तिगत एवं खाता जानकारी',
      'phone_number': 'फ़ोन नंबर',
      'primary_location': 'प्राथमिक स्थान',
      'availability_schedule': 'उपलब्धता अनुसूची',
      'verified_documents': 'सत्यापित दस्तावेज़',
      'upload_new': 'नया अपलोड करें',
      'security_app_lock': 'सुरक्षा एवं ऐप लॉक',
      'fingerprint_lock': 'फिंगरप्रिंट ऐप लॉक',
      'fingerprint_sub': 'बायोमेट्रिक फिंगरप्रिंट या पिन से ऐप लॉक करें',
      'google_2fa': 'गूगल 2FA प्रमाणक',
      'google_2fa_sub': 'खाता लॉगिन के लिए 2FA TOTP कोड जोड़ें',
      'app_prefs_lang': 'ऐप प्राथमिकताएं एवं भाषा',
      'app_language': 'ऐप भाषा',
      'logout_account': 'खाता लॉगआउट करें',
      'csr_proposals': 'प्रस्ताव',
      'csr_budgets': 'स्वीकृत बजट',
      'csr_milestones': 'मील के पत्थर',
      'csr_utilization': 'उपयोग रिपोर्ट',
      'new_proposal': 'नया सीएसआर प्रस्ताव',
      'partner_registrations': 'पार्टनर पंजीकरण',
      'referrals': 'सिफारिशें (रेफरल)',
      'camp_schedules': 'शिविर अनुसूची',
      'student_progress': 'छात्र प्रगति',
      'submit_referral': 'रेफरल सबमिट करें',
      'register_partner': 'पार्टनर पंजीकृत करें',
      'report_summaries': 'रिपोर्ट सारांश',
      'data_anomalies': 'डेटा विसंगतियां',
      'draft_impact_reports': 'प्रारूप प्रभाव रिपोर्ट',
      'approve_publish': 'रिपोर्ट स्वीकृत एवं प्रकाशित करें',
      'accessibility_title': 'सुगम्यता एवं आसान नेविगेशन',
      'text_scale_title': 'फ़ॉन्ट आकार पैमाना',
      'high_contrast_title': 'उच्च कंट्रास्ट मोड (WCAG AAA)',
      'high_contrast_sub': 'कम दृष्टि वाले उपयोगकर्ताओं के लिए रंग और टेक्स्ट स्पष्टता बढ़ाता है।',
      'screen_reader_notice': 'सभी फॉर्मों और नेविगेशन पर टॉकाबैक/वॉइसओवर स्क्रीन-रीडर लेबल सक्षम हैं।',
    },
    'bn': {
      'app_title': 'সুইজেন ফাউন্ডেশন',
      'tagline': 'সেকশন ৮ অলাভজনক | জাতিসংঘ এসডিজি সংরেখিত',
      'hero_heading': 'আপনার ১০০০ টাকা আজ একটি জীবন বদলে দিতে পারে',
      'hero_sub': 'স্বাস্থ্যসেবা, শিক্ষা ও পরিবেশ কর্মসূচির মাধ্যমে গ্রামীণ সম্প্রদায়কে ক্ষমতায়িত করুন।',
      'btn_donate_now': 'কারো হাসির কারণ হন',
      'btn_see_impact': 'আমাদের প্রভাব দেখুন',
      'nav_home': 'হোম',
      'nav_projects': 'প্রকল্পসমূহ',
      'nav_donate': 'দান করুন',
      'nav_volunteer': 'স্বেচ্ছাসেবক',
      'nav_profile': 'প্রোফাইল',
      'stat_projects': 'সক্রিয় প্রকল্প',
      'stat_beneficiaries': 'উপকৃত মানুষ',
      'stat_volunteers': 'স্বেচ্ছাসেবক',
      'stat_funds': 'সংগৃহীত অর্থ',
      'featured_projects': 'বিশেষ প্রকল্পসমূহ',
      'humanity_card': 'হিউম্যানিটি স্মার্ট আইডি',
      'ask_sweezen': 'সুইজেন এআই জিজ্ঞাসা করুন',
      'tax_benefit': '৮০জি কর ছাড় উপলব্ধ',
      'login': 'লগইন / নিবন্ধন',
      'select_language': 'অ্যাপের ভাষা নির্বাচন করুন',
    },
    'pa': {
      'app_title': 'ਸਵੀਜ਼ਨ ਫਾਊਂਡੇਸ਼ਨ',
      'tagline': 'ਧਾਰਾ 8 ਗੈਰ-ਲਾਭਕਾਰੀ | ਸੰਯੁਕਤ ਰਾਸ਼ਟਰ SDG',
      'hero_heading': 'ਤੁਹਾਡਾ ₹1000 ਅੱਜ ਕਿਸੇ ਦੀ ਜ਼ਿੰਦਗੀ ਬਦਲ ਸਕਦਾ ਹੈ',
      'hero_sub': 'ਸਿਹਤ ਸੰਭਾਲ, ਸਿੱਖਿਆ ਅਤੇ ਵਾਤਾਵਰਣ ਪ੍ਰੋਗਰਾਮਾਂ ਨਾਲ ਪੇਂਡੂ ਭਾਈਚਾਰਿਆਂ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਓ।',
      'btn_donate_now': 'ਕਿਸੇ ਦੀ ਮੁਸਕਰਾਹਟ ਦਾ ਕਾਰਨ ਬਣੋ',
      'btn_see_impact': 'ਸਾਡਾ ਪ੍ਰਭਾਵ ਦੇਖੋ',
      'nav_home': 'ਹੋਮ',
      'nav_projects': 'ਪ੍ਰੋਜੈਕਟ',
      'nav_donate': 'ਦਾਨ ਕਰੋ',
      'nav_volunteer': 'ਵਲੰਟੀਅਰ',
      'nav_profile': 'ਪ੍ਰੋਫਾਈਲ',
      'stat_projects': 'ਐਕਟਿਵ ਪ੍ਰੋਜੈਕਟ',
      'stat_beneficiaries': 'ਲਾਭਪਾਤਰੀ',
      'stat_volunteers': 'ਵਲੰਟੀਅਰ',
      'stat_funds': 'ਇਕੱਠਾ ਕੀਤਾ ਦਾਨ',
      'featured_projects': 'ਮੁੱਖ ਪ੍ਰੋਜੈਕਟ',
      'humanity_card': 'ਹਿਊਮੈਨਿਟੀ ਸਮਾਰਟ ਆਈਡੀ',
      'ask_sweezen': 'ਸਵੀਜ਼ਨ AI ਪੁੱਛੋ',
      'tax_benefit': '80G ਟੈਕਸ ਛੋਟ ਪ੍ਰਾਪਤ ਕਰੋ',
      'login': 'ਲੌਗਇਨ / ਰਜਿਸਟਰ',
      'select_language': 'ਐਪ ਭਾਸ਼ਾ ਚੁਣੋ',
    },
    'mr': {
      'app_title': 'स्वीजन फाउंडेशन',
      'tagline': 'कलम ८ ना-नफा संस्था | युएन एसडीजी संरेखित',
      'hero_heading': 'तुमचे ₹१००० आज कोणाचे तरी आयुष्य बदलू शकतात',
      'hero_sub': 'आरोग्य, शिक्षण आणि पर्यावरण कार्यक्रमांद्वारे ग्रामीण समुदायांना सक्षम करा.',
      'btn_donate_now': 'कोणाच्या तरी हास्याचे कारण बना',
      'btn_see_impact': 'आमचा प्रभाव पहा',
      'nav_home': 'होम',
      'nav_projects': 'प्रकल्प',
      'nav_donate': 'देणगी द्या',
      'nav_volunteer': 'स्वयंसेवक',
      'nav_profile': 'प्रोफाईल',
      'stat_projects': 'सक्रिय प्रकल्प',
      'stat_beneficiaries': 'लाभार्थी',
      'stat_volunteers': 'स्वयंसेवक',
      'stat_funds': 'जमा निधी',
      'featured_projects': 'प्रमुख प्रकल्प',
      'humanity_card': 'ह्युमॅनिटी स्मार्ट आयडी',
      'ask_sweezen': 'स्वीजन AI ला विचारा',
      'tax_benefit': '80G कर सवलत उपलब्ध',
      'login': 'लॉगिन / नोंदणी',
      'select_language': 'ॲपची भाषा निवडा',
    },
    'gu': {
      'app_title': 'સ્વીઝન ફાઉન્ડેશન',
      'tagline': 'કલમ 8 નોન-પ્રોફિટ | UN SDG સુસંગત',
      'hero_heading': 'તમારા ₹1000 આજે કોઈનું જીવન બદલી શકે છે',
      'hero_sub': 'આરોગ્ય સંભાળ, શિક્ષણ અને પર્યાવરણ કાર્યક્રમો દ્વારા ગ્રામીણ સમુદાયોને સશક્ત બનાવો.',
      'btn_donate_now': 'કોઈના સ્મિતનું કારણ બનો',
      'btn_see_impact': 'અમારો પ્રભાવ જુઓ',
      'nav_home': 'હોમ',
      'nav_projects': 'પ્રોજેક્ટ્સ',
      'nav_donate': 'દાન કરો',
      'nav_volunteer': 'સ્વયંસેવક',
      'nav_profile': 'પ્રોફાઇલ',
      'stat_projects': 'સક્રિય પ્રોજેક્ટ્સ',
      'stat_beneficiaries': 'લાભાર્થીઓ',
      'stat_volunteers': 'સ્વયંસેવકો',
      'stat_funds': 'એકત્રિત ફંડ',
      'featured_projects': 'મુખ્ય પ્રોજેક્ટ્સ',
      'humanity_card': 'હ્યુમેનિટી સ્માર્ટ આઈડી',
      'ask_sweezen': 'સ્વીઝન AI ને પૂછો',
      'tax_benefit': '80G કર મુક્તિ ઉપલબ્ધ',
      'login': 'લોગિન / નોંધણી',
      'select_language': 'એપ ભાષા પસંદ કરો',
    },
    'ta': {
      'app_title': 'ஸ்வீஸன் அறக்கட்டளை',
      'tagline': 'பிரிவு 8 தொண்டு நிறுவனம் | ஐநா எஸ்டிஜி',
      'hero_heading': 'உங்கள் ₹1000 இன்று ஒரு வாழ்க்கையை மாற்றும்',
      'hero_sub': 'சுகாதாரம் மற்றும் கல்வி மூலம் கிராமப்புற சமுதாயத்தை மேம்படுத்துங்கள்.',
      'btn_donate_now': 'ஒருவரின் புன்னகைக்கு காரணமாக இருங்கள்',
      'btn_see_impact': 'எங்கள் தாக்கத்தை காண்க',
      'nav_home': 'முகப்பு',
      'nav_projects': 'திட்டங்கள்',
      'nav_donate': 'நன்கொடை',
      'nav_volunteer': 'தொண்டர்',
      'nav_profile': 'சுயவிவரம்',
      'stat_projects': 'செயல்பாட்டில் உள்ள திட்டங்கள்',
      'stat_beneficiaries': 'பயனாளிகள்',
      'stat_volunteers': 'தொண்டர்கள்',
      'stat_funds': 'சேகரிக்கப்பட்ட நிதி',
      'featured_projects': 'சிறப்பு திட்டங்கள்',
      'humanity_card': 'ஹியூமானிட்டி ஸ்மார்ட் ஐடி',
      'ask_sweezen': 'ஸ்வீஸன் AI இடம் கேளுங்கள்',
      'tax_benefit': '80G வரி விலக்கு உண்டு',
      'login': 'உள்நுழைவு / பதிவு',
      'select_language': 'செயலி மொழியைத் தேர்ந்தெடுக்கவும்',
    },
    'te': {
      'app_title': 'స్వీజెన్ ఫౌండేషన్',
      'tagline': 'సెక్షన్ 8 లాభాపేక్ష లేని సంస్థ | UN SDG',
      'hero_heading': 'మీ ₹1000 ఈరోజు ఒకరి జీవితాన్ని మార్చగలవు',
      'hero_sub': 'ఆరోగ్యం మరియు విద్య ద్వారా గ్రామీణ సమాజాన్ని సాధికారపరచండి.',
      'btn_donate_now': 'ఒకరి చిరునవ్వుకు కారణం అవ్వండి',
      'btn_see_impact': 'మా ప్రభావాన్ని చూడండి',
      'nav_home': 'హోమ్',
      'nav_projects': 'ప్రాజెక్ట్‌లు',
      'nav_donate': 'విరాళం',
      'nav_volunteer': 'వాలంటీర్',
      'nav_profile': 'ప్రొఫైల్',
      'stat_projects': 'యాక్టివ్ ప్రాజెక్ట్‌లు',
      'stat_beneficiaries': 'లబ్ధిదారులు',
      'stat_volunteers': 'వాలంటీర్లు',
      'stat_funds': 'సేకరించిన నిధులు',
      'featured_projects': 'ముఖ్య ప్రాజెక్ట్‌లు',
      'humanity_card': 'హ్యుమానిటీ స్మార్ట్ ఐడీ',
      'ask_sweezen': 'స్వీజెన్ AI ని అడగండి',
      'tax_benefit': '80G పన్ను మినహాయింపు అందుబాటులో ఉంది',
      'login': 'లాగిన్ / రిజిస్టర్',
      'select_language': 'యాప్ భాషను ఎంచుకోండి',
    },
    'kn': {
      'app_title': 'ಸ್ವೀಜನ್ ಫೌಂಡೇಶನ್',
      'tagline': 'ಸೆಕ್ಷನ್ 8 ಲಾಭರಹಿತ ಸಂಸ್ಥೆ | UN SDG',
      'hero_heading': 'ನಿಮ್ಮ ₹1000 ಇಂದು ಒಬ್ಬರ ಜೀವನವನ್ನು ಬದಲಾಯಿಸಬಹುದು',
      'hero_sub': 'ಆರೋಗ್ಯ ಮತ್ತು ಶಿಕ್ಷಣದ ಮೂಲಕ ಗ್ರಾಮೀಣ ಜನರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸಿ.',
      'btn_donate_now': 'ಒಬ್ಬರ ನಗುವಿಗೆ ಕಾರಣವಾಗಿ',
      'btn_see_impact': 'ನಮ್ಮ ಪ್ರಭಾವ ನೋಡಿ',
      'nav_home': 'ಹೋಮ್',
      'nav_projects': 'ಯೋಜನೆಗಳು',
      'nav_donate': 'ದೇಣಿಗೆ',
      'nav_volunteer': 'ಸ್ವಯಂಸೇವಕ',
      'nav_profile': 'ಪ್ರೊಫೈಲ್',
      'stat_projects': 'ಸಕ್ರಿಯ ಯೋಜನೆಗಳು',
      'stat_beneficiaries': 'ಫಲಾನುಭವಿಗಳು',
      'stat_volunteers': 'ಸ್ವಯಂಸೇವಕರು',
      'stat_funds': 'ಸಂಗ್ರಹಿಸಿದ ನಿಧಿ',
      'featured_projects': 'ಪ್ರಮುಖ ಯೋಜನೆಗಳು',
      'humanity_card': 'ಹ್ಯುಮ್ಯಾನಿಟಿ ಸ್ಮಾರ್ಟ್ ಐಡಿ',
      'ask_sweezen': 'ಸ್ವೀಜನ್ AI ಕೇಳಿ',
      'tax_benefit': '80G ತೆರಿಗೆ ವಿನಾಯಿತಿ ಲಭ್ಯವಿದೆ',
      'login': 'ಲಾಗಿನ್ / ನೋಂದಣಿ',
      'select_language': 'ಆಪ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    },
    'ml': {
      'app_title': 'സ്വീസൻ ഫൗണ്ടേഷൻ',
      'tagline': 'സെക്ഷൻ 8 ലാഭരഹിത സംഘടന | UN SDG',
      'hero_heading': 'നിങ്ങളുടെ ₹1000 ഇന്ന് ഒരാളുടെ ജീവിതം മാറ്റാം',
      'hero_sub': 'ആരോഗ്യവും വിദ്യാഭ്യാസവും വഴി ഗ്രാമീണ മേഖലയെ ശാക്തീകരിക്കുക.',
      'btn_donate_now': 'ഒരാളുടെ ചിരിക്ക് കാരണമാകൂ',
      'btn_see_impact': 'ഞങ്ങളുടെ സ്വാധീനം കാണുക',
      'nav_home': 'ഹോം',
      'nav_projects': 'പദ്ധതികൾ',
      'nav_donate': 'സംഭാവന',
      'nav_volunteer': 'സന്നദ്ധപ്രവർത്തകൻ',
      'nav_profile': 'പ്രൊഫൈൽ',
      'stat_projects': 'സജീവ പദ്ധതികൾ',
      'stat_beneficiaries': 'ഗുണഭോക്താക്കൾ',
      'stat_volunteers': 'സന്നദ്ധപ്രവർത്തകർ',
      'stat_funds': 'ശേഖരിച്ച ഫണ്ട്',
      'featured_projects': 'പ്രധാന പദ്ധതികൾ',
      'humanity_card': 'ഹ്യൂമാനിറ്റി സ്മാർട്ട് ഐഡി',
      'ask_sweezen': 'സ്വീസൻ AI ചോദിക്കൂ',
      'tax_benefit': '80G നികുതി ഇളവ് ലഭ്യമാണ്',
      'login': 'ലോഗിൻ / രജിസ്റ്റർ',
      'select_language': 'ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക',
    },
    'or': {
      'app_title': 'ସ୍ୱୀଜେନ୍ ଫାଉଣ୍ଡେସନ୍',
      'tagline': 'ସେକ୍ସନ୍ ୮ ସ୍ୱେଚ୍ଛାସେବୀ ଅନୁଷ୍ଠାନ | UN SDG',
      'hero_heading': 'ଆପଣଙ୍କର ₹୧୦୦୦ ଆଜି କାହାର ଜୀବନ ବଦଳାଇପାରେ',
      'hero_sub': 'ସ୍ୱାସ୍ଥ୍ୟସେବା ଓ ଶିକ୍ଷା ମାଧ୍ୟମରେ ଗ୍ରାମୀଣ ସମାଜକୁ ସଶକ୍ତ କରନ୍ତୁ।',
      'btn_donate_now': 'କାହା ହସର କାରଣ ହୁଅନ୍ତୁ',
      'btn_see_impact': 'ଆମର ପ୍ରଭାବ ଦେଖନ୍ତୁ',
      'nav_home': 'ହୋମ୍',
      'nav_projects': 'ଯୋଜନା',
      'nav_donate': 'ଦାନ କରନ୍ତୁ',
      'nav_volunteer': 'ସ୍ୱେଚ୍ଛାସେବୀ',
      'nav_profile': 'ପ୍ରୋଫାଇଲ୍',
      'stat_projects': 'ସକ୍ରିୟ ଯୋଜନା',
      'stat_beneficiaries': 'ହିତାଧିକାରୀ',
      'stat_volunteers': 'ସ୍ୱେଚ୍ଛାସେବୀ',
      'stat_funds': 'ସଂଗୃହିତ ଅର୍ଥ',
      'featured_projects': 'ପ୍ରମୁଖ ଯୋଜନା',
      'humanity_card': 'ହିଉମାନିଟି ସ୍ମାର୍ଟ ଆଇଡି',
      'ask_sweezen': 'ସ୍ୱୀଜେନ୍ AI କୁ ପଚାରନ୍ତୁ',
      'tax_benefit': '୮୦G ଟିକସ ଛାଡ ଉପଲବ୍ଧ',
      'login': 'ଲଗଇନ୍ / ପଞ୍ଜୀକରଣ',
      'select_language': 'ଆପ୍ ଭାଷା ଚୟନ କରନ୍ତୁ',
    },
    'ur': {
      'app_title': 'سویزن فاؤنڈیشن',
      'tagline': 'سیکشن 8 غیر منافع بخش | UN SDG',
      'hero_heading': 'آپ کے ₹1000 آج کسی کی زندگی بدل سکتے ہیں',
      'hero_sub': 'صحت اور تعلیم کے ذریعے دیہی برادریوں کو بااختیار بنائیں۔',
      'btn_donate_now': 'کسی کی مسکراہٹ کی وجہ بنیں',
      'btn_see_impact': 'ہمارا اثر دیکھیں',
      'nav_home': 'ہوم',
      'nav_projects': 'منصوبے',
      'nav_donate': 'عطیہ دیں',
      'nav_volunteer': 'رضاکار',
      'nav_profile': 'پروفائل',
      'stat_projects': 'ایکٹو منصوبے',
      'stat_beneficiaries': 'مستفیدین',
      'stat_volunteers': 'رضاکار',
      'stat_funds': 'جمع شدہ رقم',
      'featured_projects': 'اہم منصوبے',
      'humanity_card': 'ہیومینیٹی اسمارٹ آئی ڈی',
      'ask_sweezen': 'سویزن AI سے پوچھیں',
      'tax_benefit': '80G ٹیکس چھوٹ دستیاب ہے',
      'login': 'لاگ ان / رجسٹر',
      'select_language': 'ایپ کی زبان منتخب کریں',
    }
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
